### ISSUE TITLE
Difference between average and fastavg kernel

### ISSUE THREAD

**Issue by gncs** [epfl-cosmo/glosim#7]
Not exactly an issue but I was wondering if you could tell me what the difference was between the `average` and `fastavg` kernel. In which cases can I use the much faster `fastavg` kernel and when should I resort to the `average` kernel?
Thank you! :)

**Comment by sandipde** [comment]
Hi gncs,
  If you refer to our original [paper](http://pubs.rsc.org/en/content/articlelanding/2016/cp/c6cp00415f#!divAbstract) where the average-soap kernel was defined, you will see that we note that the for doing the simple average doesn't need to store the full soap fingerprints but the average will be enough. This is exactly what fast average is. 

<img width="344" alt="screen shot 2018-01-19 at 15 07 30" src="https://user-images.githubusercontent.com/11316489/35154448-946756ce-fd2a-11e7-897f-ef641b05c06e.png">

However, there are situations (see our [science advance paper](http://advances.sciencemag.org/content/3/12/e1701816/tab-pdf)) where instead of taking the simple average, you want to make the average of Cij^zeta  instead of Cij. For zeta not equal to one, you can not make the above simplification and get away with storing the average value of soap fingerprints but to use the full fingerprints which are very long vectors. That makes the computation expensive. So the takeaway message is if you want to set the --zeta parameter to any value other than 1, only then you have to use average kernel. for zeta=1 the average and fastaverage are same but for the above-mentioned reason, the fastaverage would be faster than average. Let me know if that helps.

**Comment by gncs** [comment]
Thank you very much for the quick response and the good explanation! 👍

**Comment by gncs** [comment]
Actually, this [line](https://github.com/cosmo-epfl/glosim/blob/master/libmatch/structures.py#L172) confuses me now. Why do you take the result to the power of `zeta` if this kernel only works for `zeta` equals one? What am I missing?

In addition, I do have two more questions if you don't mind: could you explain the options `cotw` and `nonorm` to me, please?
Thanks a lot!

**Comment by sandipde** [comment]
Hi, Sorry for late reply. Yes.. this is indeed confusing. In the context of fast avg the zeta is used to raise the whole kernel to that power after averaging. so although the same variable name has been used the meaning of zeta is different in two contexts which made you confused. 

The nonorm is used when the normalization of the full kernel not to be performed. cotw is cutoff transition width to be used for the local environments. More details about cotw should be found in original soap paper by Gabor csyani. We have not changed the default cotw in our early works.
