### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by bartolsthoorn** [epfl-cosmo/glosim#8]
Hi, I am trying to run this code with the rematch kernel but it seems that the following dependency is outdated:

https://github.com/cosmo-epfl/glosim/blob/9e18ffa6f302142514f222b0386e7d5dcb85d84f/libmatch/lap/perm.py#L33

I installed https://github.com/sandipde/MCpermanent/ but it does not seem to match the code here.

**Comment by sandipde** [comment]
Hi,
  please use the source code at https://github.com/cosmo-epfl/glosim/tree/master/libmatch/lap/permanent-0.0.1  which is included with the glosim code ( glosim/libmatch/lap/permanent-0.0.1) . you have to build the code in the directory with 
python setup.py build 
then copy permanent.so file from build/lib*/ folder to glosim/libmatch/lap/  so that the library is in the path. This should solve the problem.

**Comment by bartolsthoorn** [comment]
Thanks for the solution (sorry for the slow reply).
